package templates

import "fmt"

// CreateMacOSAppDelegateTemplate creates the macOS AppDelegate.swift template
func CreateMacOSAppDelegateTemplate(projectName string) string {
	return `import Cocoa

@main
class AppDelegate: NSObject, NSApplicationDelegate {
    var mainWindow: MainWindow?

    func applicationDidFinishLaunching(_ notification: Notification) {
        // Initialize GoFlow runtime
        print("GoFlow: Initializing ` + projectName + `")

        // Create main window
        mainWindow = MainWindow()
        mainWindow?.makeKeyAndOrderFront(nil)

        NSApp.activate(ignoringOtherApps: true)
    }

    func applicationWillTerminate(_ notification: Notification) {
        print("GoFlow: Terminating ` + projectName + `")
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return true
    }
}
`
}

// CreateMacOSMainWindowTemplate creates the macOS MainWindow.swift template
func CreateMacOSMainWindowTemplate(projectName string) string {
	return `import Cocoa

class MainWindow: NSWindow {
    init() {
        super.init(
            contentRect: NSRect(x: 0, y: 0, width: 1200, height: 800),
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )

        self.title = "` + projectName + `"
        self.center()

        // TODO: Load GoFlow shared library and initialize engine
        setupGoFlowEngine()
    }

    private func setupGoFlowEngine() {
        // This will load the compiled Go shared library (libapp.dylib)
        // and initialize the GoFlow rendering engine

        print("GoFlow: Setting up rendering engine for ` + projectName + `")

        // Future implementation:
        // 1. Load libapp.dylib from build output
        // 2. Call Go initialization function
        // 3. Set up rendering surface
        // 4. Start event loop

        // For now, show placeholder content
        let textField = NSTextField(frame: NSRect(x: 20, y: 20, width: 760, height: 60))
        textField.stringValue = "GoFlow is initializing..."
        textField.isEditable = false
        textField.isBordered = false
        textField.backgroundColor = .clear
        contentView?.addSubview(textField)
    }
}
`
}

// CreateMacOSInfoPlistTemplate creates the macOS Info.plist template
func CreateMacOSInfoPlistTemplate(projectName, org string) string {
	bundleID := fmt.Sprintf("%s.%s", org, projectName)
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>` + projectName + `</string>
	<key>CFBundleIdentifier</key>
	<string>` + bundleID + `</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>` + projectName + `</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.14</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
`
}

// CreateMacOSXCConfigTemplate creates the macOS xcconfig template
func CreateMacOSXCConfigTemplate(projectName string) string {
	return `// GoFlow-Generated Configuration
// This file is automatically generated by goflow build

// Go shared library path
GOFLOW_GO_LIBRARY_PATH = ${PROJECT_DIR}/../build/macos/libapp.dylib

// GoFlow runtime framework path
GOFLOW_RUNTIME_FRAMEWORK_PATH = ${PROJECT_DIR}/GoFlow/Frameworks/GoFlowRuntime.framework

// Additional configuration
PRODUCT_NAME = ` + projectName + `
PRODUCT_BUNDLE_IDENTIFIER = com.goflow.` + projectName + `

// Build settings
ALWAYS_SEARCH_USER_PATHS = NO
CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
CLANG_WARN_BOOL_CONVERSION = YES
CLANG_WARN_COMMA = YES
CLANG_WARN_CONSTANT_CONVERSION = YES
CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
CLANG_WARN_EMPTY_BODY = YES
CLANG_WARN_ENUM_CONVERSION = YES
CLANG_WARN_INFINITE_RECURSION = YES
CLANG_WARN_INT_CONVERSION = YES
CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
CLANG_WARN_STRICT_PROTOTYPES = YES
CLANG_WARN_SUSPICIOUS_MOVE = YES
CLANG_WARN_UNREACHABLE_CODE = YES
CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
ENABLE_STRICT_OBJC_MSGSEND = YES
GCC_NO_COMMON_BLOCKS = YES
GCC_WARN_64_TO_32_BIT_CONVERSION = YES
GCC_WARN_ABOUT_RETURN_TYPE = YES
GCC_WARN_UNDECLARED_SELECTOR = YES
GCC_WARN_UNINITIALIZED_AUTOS = YES
GCC_WARN_UNUSED_FUNCTION = YES
GCC_WARN_UNUSED_VARIABLE = YES
`
}

// CreateMacOSReadmeTemplate creates the macOS README.md template
func CreateMacOSReadmeTemplate() string {
	return `# macOS Runner

This directory contains the macOS native shell for your GoFlow application.

## Structure

- **Runner/** - Swift code for the native macOS app shell
  - AppDelegate.swift - Application lifecycle management
  - MainWindow.swift - Main window and GoFlow engine integration
  - Info.plist - macOS application metadata

- **GoFlow/** - GoFlow-specific configuration
  - ephemeral/GoFlow-Generated.xcconfig - Auto-generated build configuration

## How It Works

This follows the same architecture as Flutter's platform embedding:

1. Your Go code in ` + "`lib/`" + ` is compiled to a shared library (` + "`libapp.dylib`" + `)
2. The Swift runner (this folder) creates a native macOS window
3. The runner loads and initializes your Go code
4. GoFlow renders your UI using Core Graphics

## Building

The ` + "`goflow build macos`" + ` command handles the full build process:

1. Compiles Go code → libapp.dylib
2. Generates xcconfig with paths
3. Builds Swift runner with Xcode
4. Links everything together
5. Creates .app bundle

## Development

For development with hot reload:

` + "```bash" + `
goflow run
` + "```" + `

This will:
- Watch for file changes
- Recompile Go code
- Reload the shared library
- Preserve app state

## Learn More

See ` + "`docs/MACOS_EMBEDDING.md`" + ` in the GoFlow repository for detailed documentation.
`
}
